### ISSUE TITLE
关于freertos下验证错误

### ISSUE THREAD

**Issue by limit2015** [SummerFalls/Microchip_CryptoAuthLib_STM32#2]
大佬请教下 我把这些代码移植到freertos下, 返回验证错误, 临界区运行也不行, 但在裸机下运行结果没问题, 这一般是哪方面得问题?

**Comment by SummerFalls** [comment]
问题描述比较模糊，不过我猜测是你的延时函数没有适配到FreeRTOS造成的。我的FreeRTOS+emWin带GUI批量烧录版本运行得非常正常。
